# Goal 1
## Given a partial permit, can we predict what classification it belongs to?

Trade permits can be messy and incomplete. Can we use this partial data to successfully predict which Purpose code the permit should belong to?

### Getting Started
- Open up the CITES trade database at https://trade.cites.org/
- Select a year range and click *Search*
- Download a Comparative Tabulation report and place it in `data/`
- Install requirements with `pip install -r requirements.txt`
- Run this notebook

In [382]:
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.pipeline import Pipeline

In [383]:
seed = 1
np.random.seed(seed)

### Importing our data
Let's import our data into a pandas dataframe and take a look at it.

In [384]:
dataframe = pd.read_csv("data/data.csv", skipinitialspace=True, dtype={
    'Importer reported quantity': float,
    'Exporter reported quantity': float
})

dataframe

,Year,App.,Taxon,Class,Order,Family,Genus,Importer,Exporter,Origin,Importer reported quantity,Exporter reported quantity,Term,Unit,Purpose,Source
0,2016,I,Aquila heliaca,Aves,Falconiformes,Accipitridae,Aquila,TR,NL,CZ,NaN,1.0,bodies,NaN,T,C
1,2016,I,Aquila heliaca,Aves,Falconiformes,Accipitridae,Aquila,XV,RS,RS,NaN,1.0,bodies,NaN,Q,O
2,2016,I,Haliaeetus albicilla,Aves,Falconiformes,Accipitridae,Haliaeetus,BE,NO,NaN,NaN,43.0,feathers,NaN,S,W
3,2016,I,Haliaeetus albicilla,Aves,Falconiformes,Accipitridae,Haliaeetus,BE,NO,NaN,NaN,43.0,specimens,NaN,S,W
4,2016,I,Haliaeetus albicilla,Aves,Falconiformes,Accipitridae,Haliaeetus,DK,IS,NaN,700.00,NaN,specimens,NaN,S,W
5,2016,I,Haliaeetus albicilla,Aves,Falconiformes,Accipitridae,Haliaeetus,XV,RS,RS,NaN,1.0,bodies,NaN,Q,O
6,2016,I,Harpia harpyja,Aves,Falconiformes,Accipitridae,Harpia,BR,FR,NaN,NaN,12.0,feathers,NaN,S,C
7,2016,I,Harpia harpyja,Aves,Falconiformes,Accipitridae,Harpia,BR,FR,NaN,NaN,4.0,feathers,NaN,S,U
8,2016,I,Harpia harpyja,Aves,Falconiformes,Accipitridae,Harpia,BR,FR,NaN,NaN,2.0,feathers,NaN,S,W
9,2016,I,Acipenser brevirostrum,Actinopteri,Acipenseriformes,Acipenseridae,Acipenser,CH,DE,NaN,NaN,4.0,live,NaN,T,C
10,2016,I,Acipenser brevirostrum,Actinopteri,Acipenseriformes,Acipenseridae,Acipenser,TW,CA,NaN,NaN,3.0,eggs (live),kg,T,D
11,2016,I,Acipenser sturio,Actinopteri,Acipenseriformes,Acipenseridae,Acipenser,US,IR,NaN,100.00,NaN,caviar,g,P,I
12,2016,I,Agave parviflora,NaN,Liliales,Agavaceae,Agave,US,TH,NaN,NaN,1.0,live,NaN,T,D
13,2016,I,Ailurus fulgens,Mammalia,Carnivora,Ailuridae,Ailurus,AU,NZ,NaN,NaN,2.0,live,NaN,Z,C
14,2016,I,Ailurus fulgens,Mammalia,Carnivora,Ailuridae,Ailurus,CA,US,NaN,1.00,1.0,live,NaN,Z,F
15,2016,I,Ailurus fulgens,Mammalia,Carnivora,Ailuridae,Ailurus,IL,DE,NaN,NaN,2.0,live,NaN,Z,C
16,2016,I,Ailurus fulgens,Mammalia,Carnivora,Ailuridae,Ailurus,JP,US,NaN,1.00,NaN,live,NaN,B,C
17,2016,I,Ailurus fulgens,Mammalia,Carnivora,Ailuridae,Ailurus,JP,US,NaN,NaN,1.0,live,NaN,Z,C
18,2016,I,Ailurus fulgens,Mammalia,Carnivora,Ailuridae,Ailurus,KP,CN,NaN,NaN,1.0,bodies,NaN,E,U
19,2016,I,Ailurus fulgens,Mammalia,Carnivora,Ailuridae,Ailurus,KR,CN,NaN,NaN,1.0,specimens,NaN,E,C
20,2016,I,Ailurus fulgens,Mammalia,Carnivora,Ailuridae,Ailurus,KR,JP,NaN,NaN,1.0,live,NaN,Z,C
21,2016,I,Ailurus fulgens,Mammalia,Carnivora,Ailuridae,Ailurus,US,CA,NaN,5.00,5.0,live,NaN,Z,C
22,2016,I,Alligator sinensis,Reptilia,Crocodylia,Alligatoridae,Alligator,KP,CN,NaN,NaN,1.0,bodies,NaN,E,U
23,2016,I,Melanosuchus niger,Reptilia,Crocodylia,Alligatoridae,Melanosuchus,US,DK,NaN,10.00,NaN,live,NaN,Z,F
24,2016,I,Anas laysanensis,Aves,Anseriformes,Anatidae,Anas,CA,US,XX,NaN,3.0,feathers,NaN,S,I
25,2016,I,Anas laysanensis,Aves,Anseriformes,Anatidae,Anas,MC,FR,XX,2.00,NaN,live,NaN,Z,I
26,2016,I,Asarcornis scutulata,Aves,Anseriformes,Anatidae,Asarcornis,GB,JE,GB,1.00,1.0,bodies,NaN,S,C
27,2016,I,Asarcornis scutulata,Aves,Anseriformes,Anatidae,Asarcornis,GB,JE,NaN,1.00,2.0,bodies,NaN,S,C
28,2016,I,Branta sandvicensis,Aves,Anseriformes,Anatidae,Branta,CN,GB,NaN,1.00,NaN,bodies,NaN,Q,C
29,2016,I,Branta sandvicensis,Aves,Anseriformes,Anatidae,Branta,MC,FR,XX,2.00,NaN,live,NaN,Z,I
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75861,2017,II,Thalurania furcata,Aves,Apodiformes,Trochilidae,Thalurania,US,PE,NaN,NaN,22.0,specimens,NaN,S,W
75862,2017,II,Threnetes niger,Aves,Apodiformes,Trochilidae,Threnetes,US,PE,NaN,NaN,16.0,specimens,NaN,S,W
75863,2017,II,Ursus arctos,Mammalia,Carnivora,Ursidae,Ursus,BG,RU,NaN,1.00,NaN,trophies,NaN,H,W
75864,2017,II,Varanus niloticus,Reptilia,Sauria,Varanidae,Varanus,MG,FR,TD,459.00,NaN,skin pieces,NaN,T,W
75865,2017,II,Varanus salvator,Reptilia,Sauria,Varanidae,Varanus,CR,US,NaN,1.00,NaN,live,NaN,T,C
75866,2017,II,Varanus salvator,Reptilia,Sauria,Varanidae,Varanus,MO,FR,ID,1.00,NaN,leather products (small),NaN,T,W
75867,2017,II,Varanus salvator,Reptilia,Sauria,Varanidae,Varanus,MO,FR,MY,2.00,NaN,leather products (small),NaN,T,W
75868,2017,II,Varanus salvator,Reptilia,Sauria,Varanidae,Varanus,MO,GB,ID,2.00,NaN,leather products (small),NaN,T,W
75869,2017,II,Varanus salvator,Reptilia,Sauria,Varanidae,Varanus,MO,IT,ID,8.00,NaN,leather products (small),NaN,T,W
75870,2017,II,Varanus salvator,Reptilia,Sauria,Varanidae,Varanus,US,CO,ID,NaN,8.0,leather products (small),NaN,T,W
75871,2017,II,Varanus salvator,Reptilia,Sauria,Varanidae,Varanus,US,CR,NaN,NaN,21.0,live,NaN,T,C
75872,2017,II,Varanus salvator,Reptilia,Sauria,Varanidae,Varanus,XX,CO,ID,NaN,1.0,leather products (small),NaN,T,W
75873,2017,II,Dioon spinulosum,NaN,Cycadales,Zamiaceae,Dioon,NL,CR,NaN,NaN,1500.0,live,NaN,T,A
75874,2017,II,Zamiaceae spp.,NaN,Cycadales,Zamiaceae,NaN,DE,AO,NaN,NaN,2.0,specimens,NaN,S,W
75875,2017,II,Zamia integrifolia,NaN,Cycadales,Zamiaceae,Zamia,NL,CR,NaN,NaN,1500.0,live,NaN,T,A
75876,2017,II,Scleractinia spp.,Anthozoa,Scleractinia,NaN,NaN,DE,AO,NaN,NaN,50.0,raw corals,kg,S,W
75877,2017,III,Canis aureus,Mammalia,Carnivora,Canidae,Canis,DE,ET,NaN,NaN,1.0,skins,NaN,H,W
75878,2017,III,Canis aureus,Mammalia,Carnivora,Canidae,Canis,US,ET,NaN,NaN,7.0,trophies,NaN,H,W
75879,2017,III,Sarcoramphus papa,Aves,Falconiformes,Cathartidae,Sarcoramphus,JP,PE,NaN,NaN,2.0,live,NaN,T,F
75880,2017,III,Dipteryx panamensis,NaN,Fabales,Leguminosae,Dipteryx,CR,NI,NaN,19.55,NaN,sawn wood,m3,T,W
75881,2017,III,Choloepus hoffmanni,Mammalia,Pilosa,Megalonychidae,Choloepus,US,CR,NaN,NaN,5.0,bones,NaN,S,W
75882,2017,III,Choloepus hoffmanni,Mammalia,Pilosa,Megalonychidae,Choloepus,US,CR,NaN,NaN,96.0,hair,NaN,S,W
75883,2017,III,Choloepus hoffmanni,Mammalia,Pilosa,Megalonychidae,Choloepus,US,CR,NaN,NaN,452.0,specimens,NaN,S,W
75884,2017,III,Cedrela odorata,NaN,Sapindales,Meliaceae,Cedrela,CR,IN,NaN,20.30,NaN,timber,m3,T,A
75885,2017,III,Cedrela odorata,NaN,Sapindales,Meliaceae,Cedrela,CR,PR,NaN,17.66,NaN,timber,m3,T,A
75886,2017,III,Cedrela odorata,NaN,Sapindales,Meliaceae,Cedrela,CR,US,NaN,8.67,NaN,sawn wood,m3,T,A
75887,2017,III,Cedrela odorata,NaN,Sapindales,Meliaceae,Cedrela,IN,CR,NaN,NaN,20.3,timber,m3,T,W
75888,2017,III,Daboia russelii,Reptilia,Serpentes,Viperidae,Daboia,RS,IT,US,200.00,NaN,specimens,NaN,T,F
75889,2017,III,Civettictis civetta,Mammalia,Carnivora,Viverridae,Civettictis,FR,ET,NaN,NaN,635.1,musk,kg,T,R
75890,2017,III,Civettictis civetta,Mammalia,Carnivora,Viverridae,Civettictis,KR,ET,NaN,NaN,480.0,musk,kg,T,R

### Formatting the data
The Year and App. columns probably aren't going to matter to us in how we classify these records, so let's drop those first...
We'll also remove any additional whitespace from the column names to make things easier to deal with later on...

In [385]:
dataframe.columns = dataframe.columns.str.strip()
dataframe = dataframe.drop(columns=['Year', 'App.'])

dataframe

,Taxon,Class,Order,Family,Genus,Importer,Exporter,Origin,Importer reported quantity,Exporter reported quantity,Term,Unit,Purpose,Source
0,Aquila heliaca,Aves,Falconiformes,Accipitridae,Aquila,TR,NL,CZ,NaN,1.0,bodies,NaN,T,C
1,Aquila heliaca,Aves,Falconiformes,Accipitridae,Aquila,XV,RS,RS,NaN,1.0,bodies,NaN,Q,O
2,Haliaeetus albicilla,Aves,Falconiformes,Accipitridae,Haliaeetus,BE,NO,NaN,NaN,43.0,feathers,NaN,S,W
3,Haliaeetus albicilla,Aves,Falconiformes,Accipitridae,Haliaeetus,BE,NO,NaN,NaN,43.0,specimens,NaN,S,W
4,Haliaeetus albicilla,Aves,Falconiformes,Accipitridae,Haliaeetus,DK,IS,NaN,700.00,NaN,specimens,NaN,S,W
5,Haliaeetus albicilla,Aves,Falconiformes,Accipitridae,Haliaeetus,XV,RS,RS,NaN,1.0,bodies,NaN,Q,O
6,Harpia harpyja,Aves,Falconiformes,Accipitridae,Harpia,BR,FR,NaN,NaN,12.0,feathers,NaN,S,C
7,Harpia harpyja,Aves,Falconiformes,Accipitridae,Harpia,BR,FR,NaN,NaN,4.0,feathers,NaN,S,U
8,Harpia harpyja,Aves,Falconiformes,Accipitridae,Harpia,BR,FR,NaN,NaN,2.0,feathers,NaN,S,W
9,Acipenser brevirostrum,Actinopteri,Acipenseriformes,Acipenseridae,Acipenser,CH,DE,NaN,NaN,4.0,live,NaN,T,C
10,Acipenser brevirostrum,Actinopteri,Acipenseriformes,Acipenseridae,Acipenser,TW,CA,NaN,NaN,3.0,eggs (live),kg,T,D
11,Acipenser sturio,Actinopteri,Acipenseriformes,Acipenseridae,Acipenser,US,IR,NaN,100.00,NaN,caviar,g,P,I
12,Agave parviflora,NaN,Liliales,Agavaceae,Agave,US,TH,NaN,NaN,1.0,live,NaN,T,D
13,Ailurus fulgens,Mammalia,Carnivora,Ailuridae,Ailurus,AU,NZ,NaN,NaN,2.0,live,NaN,Z,C
14,Ailurus fulgens,Mammalia,Carnivora,Ailuridae,Ailurus,CA,US,NaN,1.00,1.0,live,NaN,Z,F
15,Ailurus fulgens,Mammalia,Carnivora,Ailuridae,Ailurus,IL,DE,NaN,NaN,2.0,live,NaN,Z,C
16,Ailurus fulgens,Mammalia,Carnivora,Ailuridae,Ailurus,JP,US,NaN,1.00,NaN,live,NaN,B,C
17,Ailurus fulgens,Mammalia,Carnivora,Ailuridae,Ailurus,JP,US,NaN,NaN,1.0,live,NaN,Z,C
18,Ailurus fulgens,Mammalia,Carnivora,Ailuridae,Ailurus,KP,CN,NaN,NaN,1.0,bodies,NaN,E,U
19,Ailurus fulgens,Mammalia,Carnivora,Ailuridae,Ailurus,KR,CN,NaN,NaN,1.0,specimens,NaN,E,C
20,Ailurus fulgens,Mammalia,Carnivora,Ailuridae,Ailurus,KR,JP,NaN,NaN,1.0,live,NaN,Z,C
21,Ailurus fulgens,Mammalia,Carnivora,Ailuridae,Ailurus,US,CA,NaN,5.00,5.0,live,NaN,Z,C
22,Alligator sinensis,Reptilia,Crocodylia,Alligatoridae,Alligator,KP,CN,NaN,NaN,1.0,bodies,NaN,E,U
23,Melanosuchus niger,Reptilia,Crocodylia,Alligatoridae,Melanosuchus,US,DK,NaN,10.00,NaN,live,NaN,Z,F
24,Anas laysanensis,Aves,Anseriformes,Anatidae,Anas,CA,US,XX,NaN,3.0,feathers,NaN,S,I
25,Anas laysanensis,Aves,Anseriformes,Anatidae,Anas,MC,FR,XX,2.00,NaN,live,NaN,Z,I
26,Asarcornis scutulata,Aves,Anseriformes,Anatidae,Asarcornis,GB,JE,GB,1.00,1.0,bodies,NaN,S,C
27,Asarcornis scutulata,Aves,Anseriformes,Anatidae,Asarcornis,GB,JE,NaN,1.00,2.0,bodies,NaN,S,C
28,Branta sandvicensis,Aves,Anseriformes,Anatidae,Branta,CN,GB,NaN,1.00,NaN,bodies,NaN,Q,C
29,Branta sandvicensis,Aves,Anseriformes,Anatidae,Branta,MC,FR,XX,2.00,NaN,live,NaN,Z,I
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75861,Thalurania furcata,Aves,Apodiformes,Trochilidae,Thalurania,US,PE,NaN,NaN,22.0,specimens,NaN,S,W
75862,Threnetes niger,Aves,Apodiformes,Trochilidae,Threnetes,US,PE,NaN,NaN,16.0,specimens,NaN,S,W
75863,Ursus arctos,Mammalia,Carnivora,Ursidae,Ursus,BG,RU,NaN,1.00,NaN,trophies,NaN,H,W
75864,Varanus niloticus,Reptilia,Sauria,Varanidae,Varanus,MG,FR,TD,459.00,NaN,skin pieces,NaN,T,W
75865,Varanus salvator,Reptilia,Sauria,Varanidae,Varanus,CR,US,NaN,1.00,NaN,live,NaN,T,C
75866,Varanus salvator,Reptilia,Sauria,Varanidae,Varanus,MO,FR,ID,1.00,NaN,leather products (small),NaN,T,W
75867,Varanus salvator,Reptilia,Sauria,Varanidae,Varanus,MO,FR,MY,2.00,NaN,leather products (small),NaN,T,W
75868,Varanus salvator,Reptilia,Sauria,Varanidae,Varanus,MO,GB,ID,2.00,NaN,leather products (small),NaN,T,W
75869,Varanus salvator,Reptilia,Sauria,Varanidae,Varanus,MO,IT,ID,8.00,NaN,leather products (small),NaN,T,W
75870,Varanus salvator,Reptilia,Sauria,Varanidae,Varanus,US,CO,ID,NaN,8.0,leather products (small),NaN,T,W
75871,Varanus salvator,Reptilia,Sauria,Varanidae,Varanus,US,CR,NaN,NaN,21.0,live,NaN,T,C
75872,Varanus salvator,Reptilia,Sauria,Varanidae,Varanus,XX,CO,ID,NaN,1.0,leather products (small),NaN,T,W
75873,Dioon spinulosum,NaN,Cycadales,Zamiaceae,Dioon,NL,CR,NaN,NaN,1500.0,live,NaN,T,A
75874,Zamiaceae spp.,NaN,Cycadales,Zamiaceae,NaN,DE,AO,NaN,NaN,2.0,specimens,NaN,S,W
75875,Zamia integrifolia,NaN,Cycadales,Zamiaceae,Zamia,NL,CR,NaN,NaN,1500.0,live,NaN,T,A
75876,Scleractinia spp.,Anthozoa,Scleractinia,NaN,NaN,DE,AO,NaN,NaN,50.0,raw corals,kg,S,W
75877,Canis aureus,Mammalia,Carnivora,Canidae,Canis,DE,ET,NaN,NaN,1.0,skins,NaN,H,W
75878,Canis aureus,Mammalia,Carnivora,Canidae,Canis,US,ET,NaN,NaN,7.0,trophies,NaN,H,W
75879,Sarcoramphus papa,Aves,Falconiformes,Cathartidae,Sarcoramphus,JP,PE,NaN,NaN,2.0,live,NaN,T,F
75880,Dipteryx panamensis,NaN,Fabales,Leguminosae,Dipteryx,CR,NI,NaN,19.55,NaN,sawn wood,m3,T,W
75881,Choloepus hoffmanni,Mammalia,Pilosa,Megalonychidae,Choloepus,US,CR,NaN,NaN,5.0,bones,NaN,S,W
75882,Choloepus hoffmanni,Mammalia,Pilosa,Megalonychidae,Choloepus,US,CR,NaN,NaN,96.0,hair,NaN,S,W
75883,Choloepus hoffmanni,Mammalia,Pilosa,Megalonychidae,Choloepus,US,CR,NaN,NaN,452.0,specimens,NaN,S,W
75884,Cedrela odorata,NaN,Sapindales,Meliaceae,Cedrela,CR,IN,NaN,20.30,NaN,timber,m3,T,A
75885,Cedrela odorata,NaN,Sapindales,Meliaceae,Cedrela,CR,PR,NaN,17.66,NaN,timber,m3,T,A
75886,Cedrela odorata,NaN,Sapindales,Meliaceae,Cedrela,CR,US,NaN,8.67,NaN,sawn wood,m3,T,A
75887,Cedrela odorata,NaN,Sapindales,Meliaceae,Cedrela,IN,CR,NaN,NaN,20.3,timber,m3,T,W
75888,Daboia russelii,Reptilia,Serpentes,Viperidae,Daboia,RS,IT,US,200.00,NaN,specimens,NaN,T,F
75889,Civettictis civetta,Mammalia,Carnivora,Viverridae,Civettictis,FR,ET,NaN,NaN,635.1,musk,kg,T,R
75890,Civettictis civetta,Mammalia,Carnivora,Viverridae,Civettictis,KR,ET,NaN,NaN,480.0,musk,kg,T,R

We're going to have to replace those NaN values in the reported quantities columns...

In [386]:
dataframe['Importer reported quantity'].fillna(0, inplace=True)
dataframe['Exporter reported quantity'].fillna(0, inplace=True)

dataframe

,Taxon,Class,Order,Family,Genus,Importer,Exporter,Origin,Importer reported quantity,Exporter reported quantity,Term,Unit,Purpose,Source
0,Aquila heliaca,Aves,Falconiformes,Accipitridae,Aquila,TR,NL,CZ,0.00,1.0,bodies,NaN,T,C
1,Aquila heliaca,Aves,Falconiformes,Accipitridae,Aquila,XV,RS,RS,0.00,1.0,bodies,NaN,Q,O
2,Haliaeetus albicilla,Aves,Falconiformes,Accipitridae,Haliaeetus,BE,NO,NaN,0.00,43.0,feathers,NaN,S,W
3,Haliaeetus albicilla,Aves,Falconiformes,Accipitridae,Haliaeetus,BE,NO,NaN,0.00,43.0,specimens,NaN,S,W
4,Haliaeetus albicilla,Aves,Falconiformes,Accipitridae,Haliaeetus,DK,IS,NaN,700.00,0.0,specimens,NaN,S,W
5,Haliaeetus albicilla,Aves,Falconiformes,Accipitridae,Haliaeetus,XV,RS,RS,0.00,1.0,bodies,NaN,Q,O
6,Harpia harpyja,Aves,Falconiformes,Accipitridae,Harpia,BR,FR,NaN,0.00,12.0,feathers,NaN,S,C
7,Harpia harpyja,Aves,Falconiformes,Accipitridae,Harpia,BR,FR,NaN,0.00,4.0,feathers,NaN,S,U
8,Harpia harpyja,Aves,Falconiformes,Accipitridae,Harpia,BR,FR,NaN,0.00,2.0,feathers,NaN,S,W
9,Acipenser brevirostrum,Actinopteri,Acipenseriformes,Acipenseridae,Acipenser,CH,DE,NaN,0.00,4.0,live,NaN,T,C
10,Acipenser brevirostrum,Actinopteri,Acipenseriformes,Acipenseridae,Acipenser,TW,CA,NaN,0.00,3.0,eggs (live),kg,T,D
11,Acipenser sturio,Actinopteri,Acipenseriformes,Acipenseridae,Acipenser,US,IR,NaN,100.00,0.0,caviar,g,P,I
12,Agave parviflora,NaN,Liliales,Agavaceae,Agave,US,TH,NaN,0.00,1.0,live,NaN,T,D
13,Ailurus fulgens,Mammalia,Carnivora,Ailuridae,Ailurus,AU,NZ,NaN,0.00,2.0,live,NaN,Z,C
14,Ailurus fulgens,Mammalia,Carnivora,Ailuridae,Ailurus,CA,US,NaN,1.00,1.0,live,NaN,Z,F
15,Ailurus fulgens,Mammalia,Carnivora,Ailuridae,Ailurus,IL,DE,NaN,0.00,2.0,live,NaN,Z,C
16,Ailurus fulgens,Mammalia,Carnivora,Ailuridae,Ailurus,JP,US,NaN,1.00,0.0,live,NaN,B,C
17,Ailurus fulgens,Mammalia,Carnivora,Ailuridae,Ailurus,JP,US,NaN,0.00,1.0,live,NaN,Z,C
18,Ailurus fulgens,Mammalia,Carnivora,Ailuridae,Ailurus,KP,CN,NaN,0.00,1.0,bodies,NaN,E,U
19,Ailurus fulgens,Mammalia,Carnivora,Ailuridae,Ailurus,KR,CN,NaN,0.00,1.0,specimens,NaN,E,C
20,Ailurus fulgens,Mammalia,Carnivora,Ailuridae,Ailurus,KR,JP,NaN,0.00,1.0,live,NaN,Z,C
21,Ailurus fulgens,Mammalia,Carnivora,Ailuridae,Ailurus,US,CA,NaN,5.00,5.0,live,NaN,Z,C
22,Alligator sinensis,Reptilia,Crocodylia,Alligatoridae,Alligator,KP,CN,NaN,0.00,1.0,bodies,NaN,E,U
23,Melanosuchus niger,Reptilia,Crocodylia,Alligatoridae,Melanosuchus,US,DK,NaN,10.00,0.0,live,NaN,Z,F
24,Anas laysanensis,Aves,Anseriformes,Anatidae,Anas,CA,US,XX,0.00,3.0,feathers,NaN,S,I
25,Anas laysanensis,Aves,Anseriformes,Anatidae,Anas,MC,FR,XX,2.00,0.0,live,NaN,Z,I
26,Asarcornis scutulata,Aves,Anseriformes,Anatidae,Asarcornis,GB,JE,GB,1.00,1.0,bodies,NaN,S,C
27,Asarcornis scutulata,Aves,Anseriformes,Anatidae,Asarcornis,GB,JE,NaN,1.00,2.0,bodies,NaN,S,C
28,Branta sandvicensis,Aves,Anseriformes,Anatidae,Branta,CN,GB,NaN,1.00,0.0,bodies,NaN,Q,C
29,Branta sandvicensis,Aves,Anseriformes,Anatidae,Branta,MC,FR,XX,2.00,0.0,live,NaN,Z,I
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75861,Thalurania furcata,Aves,Apodiformes,Trochilidae,Thalurania,US,PE,NaN,0.00,22.0,specimens,NaN,S,W
75862,Threnetes niger,Aves,Apodiformes,Trochilidae,Threnetes,US,PE,NaN,0.00,16.0,specimens,NaN,S,W
75863,Ursus arctos,Mammalia,Carnivora,Ursidae,Ursus,BG,RU,NaN,1.00,0.0,trophies,NaN,H,W
75864,Varanus niloticus,Reptilia,Sauria,Varanidae,Varanus,MG,FR,TD,459.00,0.0,skin pieces,NaN,T,W
75865,Varanus salvator,Reptilia,Sauria,Varanidae,Varanus,CR,US,NaN,1.00,0.0,live,NaN,T,C
75866,Varanus salvator,Reptilia,Sauria,Varanidae,Varanus,MO,FR,ID,1.00,0.0,leather products (small),NaN,T,W
75867,Varanus salvator,Reptilia,Sauria,Varanidae,Varanus,MO,FR,MY,2.00,0.0,leather products (small),NaN,T,W
75868,Varanus salvator,Reptilia,Sauria,Varanidae,Varanus,MO,GB,ID,2.00,0.0,leather products (small),NaN,T,W
75869,Varanus salvator,Reptilia,Sauria,Varanidae,Varanus,MO,IT,ID,8.00,0.0,leather products (small),NaN,T,W
75870,Varanus salvator,Reptilia,Sauria,Varanidae,Varanus,US,CO,ID,0.00,8.0,leather products (small),NaN,T,W
75871,Varanus salvator,Reptilia,Sauria,Varanidae,Varanus,US,CR,NaN,0.00,21.0,live,NaN,T,C
75872,Varanus salvator,Reptilia,Sauria,Varanidae,Varanus,XX,CO,ID,0.00,1.0,leather products (small),NaN,T,W
75873,Dioon spinulosum,NaN,Cycadales,Zamiaceae,Dioon,NL,CR,NaN,0.00,1500.0,live,NaN,T,A
75874,Zamiaceae spp.,NaN,Cycadales,Zamiaceae,NaN,DE,AO,NaN,0.00,2.0,specimens,NaN,S,W
75875,Zamia integrifolia,NaN,Cycadales,Zamiaceae,Zamia,NL,CR,NaN,0.00,1500.0,live,NaN,T,A
75876,Scleractinia spp.,Anthozoa,Scleractinia,NaN,NaN,DE,AO,NaN,0.00,50.0,raw corals,kg,S,W
75877,Canis aureus,Mammalia,Carnivora,Canidae,Canis,DE,ET,NaN,0.00,1.0,skins,NaN,H,W
75878,Canis aureus,Mammalia,Carnivora,Canidae,Canis,US,ET,NaN,0.00,7.0,trophies,NaN,H,W
75879,Sarcoramphus papa,Aves,Falconiformes,Cathartidae,Sarcoramphus,JP,PE,NaN,0.00,2.0,live,NaN,T,F
75880,Dipteryx panamensis,NaN,Fabales,Leguminosae,Dipteryx,CR,NI,NaN,19.55,0.0,sawn wood,m3,T,W
75881,Choloepus hoffmanni,Mammalia,Pilosa,Megalonychidae,Choloepus,US,CR,NaN,0.00,5.0,bones,NaN,S,W
75882,Choloepus hoffmanni,Mammalia,Pilosa,Megalonychidae,Choloepus,US,CR,NaN,0.00,96.0,hair,NaN,S,W
75883,Choloepus hoffmanni,Mammalia,Pilosa,Megalonychidae,Choloepus,US,CR,NaN,0.00,452.0,specimens,NaN,S,W
75884,Cedrela odorata,NaN,Sapindales,Meliaceae,Cedrela,CR,IN,NaN,20.30,0.0,timber,m3,T,A
75885,Cedrela odorata,NaN,Sapindales,Meliaceae,Cedrela,CR,PR,NaN,17.66,0.0,timber,m3,T,A
75886,Cedrela odorata,NaN,Sapindales,Meliaceae,Cedrela,CR,US,NaN,8.67,0.0,sawn wood,m3,T,A
75887,Cedrela odorata,NaN,Sapindales,Meliaceae,Cedrela,IN,CR,NaN,0.00,20.3,timber,m3,T,W
75888,Daboia russelii,Reptilia,Serpentes,Viperidae,Daboia,RS,IT,US,200.00,0.0,specimens,NaN,T,F
75889,Civettictis civetta,Mammalia,Carnivora,Viverridae,Civettictis,FR,ET,NaN,0.00,635.1,musk,kg,T,R
75890,Civettictis civetta,Mammalia,Carnivora,Viverridae,Civettictis,KR,ET,NaN,0.00,480.0,musk,kg,T,R

We have a lot of text data in the form of ISO country codes, and specialist categories. We'll need to encode these as one hot vectors in the next step so that our neural net can understand them. We'll grab a list of all the columns we'll need to encode first and remove the ones we don't want to encode (the numeric columns)

In [387]:
print("Number of Columns: ", len(dataframe.columns))
columns = list(dataframe.columns)
columns.remove('Importer reported quantity')
columns.remove('Exporter reported quantity')
columns.remove('Purpose')
print(columns)

Number of Columns:  14
['Taxon', 'Class', 'Order', 'Family', 'Genus', 'Importer', 'Exporter', 'Origin', 'Term', 'Unit', 'Source']

### Encoding our labels and data

In order to test the performance of our neural net, we'll need to split up our data into the data, and their corresponding classifications. 

The purpose column will be what we are going to attempt to predict (notice we removed it from the list of columns we'd like to one hot encode already).

Let's pop off our labels from our dataframe, and keep them separate...

In [388]:
labels = dataframe.pop('Purpose')

labels

0        T
1        Q
2        S
3        S
4        S
5        Q
6        S
7        S
8        S
9        T
10       T
11       P
12       T
13       Z
14       Z
15       Z
16       B
17       Z
18       E
19       E
20       Z
21       Z
22       E
23       Z
24       S
25       Z
26       S
27       S
28       Q
29       Z
        ..
75861    S
75862    S
75863    H
75864    T
75865    T
75866    T
75867    T
75868    T
75869    T
75870    T
75871    T
75872    T
75873    T
75874    S
75875    T
75876    S
75877    H
75878    H
75879    T
75880    T
75881    S
75882    S
75883    S
75884    T
75885    T
75886    T
75887    T
75888    T
75889    T
75890    T
Name: Purpose, Length: 75891, dtype: object

We'll need to convert our classifications into one hot vectors...

In [389]:
labels = pd.get_dummies(labels)

labels

       B  E  G  H  L  M  N  P  Q  S  T  Z
0      0  0  0  0  0  0  0  0  0  0  1  0
1      0  0  0  0  0  0  0  0  1  0  0  0
2      0  0  0  0  0  0  0  0  0  1  0  0
3      0  0  0  0  0  0  0  0  0  1  0  0
4      0  0  0  0  0  0  0  0  0  1  0  0
5      0  0  0  0  0  0  0  0  1  0  0  0
6      0  0  0  0  0  0  0  0  0  1  0  0
7      0  0  0  0  0  0  0  0  0  1  0  0
8      0  0  0  0  0  0  0  0  0  1  0  0
9      0  0  0  0  0  0  0  0  0  0  1  0
10     0  0  0  0  0  0  0  0  0  0  1  0
11     0  0  0  0  0  0  0  1  0  0  0  0
12     0  0  0  0  0  0  0  0  0  0  1  0
13     0  0  0  0  0  0  0  0  0  0  0  1
14     0  0  0  0  0  0  0  0  0  0  0  1
15     0  0  0  0  0  0  0  0  0  0  0  1
16     1  0  0  0  0  0  0  0  0  0  0  0
17     0  0  0  0  0  0  0  0  0  0  0  1
18     0  1  0  0  0  0  0  0  0  0  0  0
19     0  1  0  0  0  0  0  0  0  0  0  0
20     0  0  0  0  0  0  0  0  0  0  0  1
21     0  0  0  0  0  0  0  0  0  0  0  1
22     0  1  0  0  0  0  0  0  0  0  0  0
23     0  0  0  0  0  0  0  0  0  0  0  1
24     0  0  0  0  0  0  0  0  0  1  0  0
25     0  0  0  0  0  0  0  0  0  0  0  1
26     0  0  0  0  0  0  0  0  0  1  0  0
27     0  0  0  0  0  0  0  0  0  1  0  0
28     0  0  0  0  0  0  0  0  1  0  0  0
29     0  0  0  0  0  0  0  0  0  0  0  1
...   .. .. .. .. .. .. .. .. .. .. .. ..
75861  0  0  0  0  0  0  0  0  0  1  0  0
75862  0  0  0  0  0  0  0  0  0  1  0  0
75863  0  0  0  1  0  0  0  0  0  0  0  0
75864  0  0  0  0  0  0  0  0  0  0  1  0
75865  0  0  0  0  0  0  0  0  0  0  1  0
75866  0  0  0  0  0  0  0  0  0  0  1  0
75867  0  0  0  0  0  0  0  0  0  0  1  0
75868  0  0  0  0  0  0  0  0  0  0  1  0
75869  0  0  0  0  0  0  0  0  0  0  1  0
75870  0  0  0  0  0  0  0  0  0  0  1  0
75871  0  0  0  0  0  0  0  0  0  0  1  0
75872  0  0  0  0  0  0  0  0  0  0  1  0
75873  0  0  0  0  0  0  0  0  0  0  1  0
75874  0  0  0  0  0  0  0  0  0  1  0  0
75875  0  0  0  0  0  0  0  0  0  0  1  0
75876  0  0  0  0  0  0  0  0  0  1  0  0
75877  0  0  0  1  0  0  0  0  0  0  0  0
75878  0  0  0  1  0  0  0  0  0  0  0  0
75879  0  0  0  0  0  0  0  0  0  0  1  0
75880  0  0  0  0  0  0  0  0  0  0  1  0
75881  0  0  0  0  0  0  0  0  0  1  0  0
75882  0  0  0  0  0  0  0  0  0  1  0  0
75883  0  0  0  0  0  0  0  0  0  1  0  0
75884  0  0  0  0  0  0  0  0  0  0  1  0
75885  0  0  0  0  0  0  0  0  0  0  1  0
75886  0  0  0  0  0  0  0  0  0  0  1  0
75887  0  0  0  0  0  0  0  0  0  0  1  0
75888  0  0  0  0  0  0  0  0  0  0  1  0
75889  0  0  0  0  0  0  0  0  0  0  1  0
75890  0  0  0  0  0  0  0  0  0  0  1  0

[75891 rows x 12 columns]

Next we'll create one hot vectors for the rest of our datatable and call this *data*

In [390]:
data = pd.get_dummies(dataframe, columns=columns)

data

,Importer reported quantity,Exporter reported quantity,Taxon_Abronia graminea,Taxon_Acampe papillosa,Taxon_Acampe praemorsa,Taxon_Acampe rigida,Taxon_Acampe spp.,Taxon_Acanthastrea amakusensis,Taxon_Acanthastrea bowerbanki,Taxon_Acanthastrea echinata,...,Source_A,Source_C,Source_D,Source_F,Source_I,Source_O,Source_R,Source_U,Source_W,Source_X
0,0.00,1.0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1,0.00,1.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2,0.00,43.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,0.00,43.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
4,700.00,0.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
5,0.00,1.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
6,0.00,12.0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
7,0.00,4.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
8,0.00,2.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
9,0.00,4.0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
10,0.00,3.0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
11,100.00,0.0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
12,0.00,1.0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
13,0.00,2.0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
14,1.00,1.0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
15,0.00,2.0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
16,1.00,0.0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
17,0.00,1.0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
18,0.00,1.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
19,0.00,1.0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
20,0.00,1.0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
21,5.00,5.0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
22,0.00,1.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
23,10.00,0.0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
24,0.00,3.0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
25,2.00,0.0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
26,1.00,1.0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
27,1.00,2.0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
28,1.00,0.0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
29,2.00,0.0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75861,0.00,22.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
75862,0.00,16.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
75863,1.00,0.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
75864,459.00,0.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
75865,1.00,0.0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
75866,1.00,0.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
75867,2.00,0.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
75868,2.00,0.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
75869,8.00,0.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
75870,0.00,8.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
75871,0.00,21.0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
75872,0.00,1.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
75873,0.00,1500.0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
75874,0.00,2.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
75875,0.00,1500.0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
75876,0.00,50.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
75877,0.00,1.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
75878,0.00,7.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
75879,0.00,2.0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
75880,19.55,0.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
75881,0.00,5.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
75882,0.00,96.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
75883,0.00,452.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
75884,20.30,0.0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
75885,17.66,0.0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
75886,8.67,0.0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
75887,0.00,20.3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
75888,200.00,0.0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
75889,0.00,635.1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
75890,0.00,480.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0

Our data is looking better, but to make things easier on our model, we can scale everything to between 0-1...

In [391]:
scaler      = MinMaxScaler(feature_range=(0, 1))
data_scaled = scaler.fit_transform(data)
data        = pd.DataFrame(data_scaled)

data

,0,1,2,3,4,5,6,7,8,9,...,9390,9391,9392,9393,9394,9395,9396,9397,9398,9399
0,0.000000e+00,4.641746e-08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.000000e+00,4.641746e-08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,0.000000e+00,1.995951e-06,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.000000e+00,1.995951e-06,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,3.585151e-05,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
5,0.000000e+00,4.641746e-08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
6,0.000000e+00,5.570095e-07,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,0.000000e+00,1.856698e-07,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
8,0.000000e+00,9.283492e-08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
9,0.000000e+00,1.856698e-07,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,0.000000e+00,1.392524e-07,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,5.121645e-06,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
12,0.000000e+00,4.641746e-08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,0.000000e+00,9.283492e-08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,5.121645e-08,4.641746e-08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
15,0.000000e+00,9.283492e-08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,5.121645e-08,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,0.000000e+00,4.641746e-08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,0.000000e+00,4.641746e-08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
19,0.000000e+00,4.641746e-08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,0.000000e+00,4.641746e-08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,2.560822e-07,2.320873e-07,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,0.000000e+00,4.641746e-08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
23,5.121645e-07,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
24,0.000000e+00,1.392524e-07,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
25,1.024329e-07,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
26,5.121645e-08,4.641746e-08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,5.121645e-08,9.283492e-08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,5.121645e-08,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,1.024329e-07,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75861,0.000000e+00,1.021184e-06,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
75862,0.000000e+00,7.426793e-07,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
75863,5.121645e-08,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
75864,2.350835e-05,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
75865,5.121645e-08,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
75866,5.121645e-08,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
75867,1.024329e-07,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
75868,1.024329e-07,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
75869,4.097316e-07,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
75870,0.000000e+00,3.713397e-07,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
75871,0.000000e+00,9.747666e-07,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
75872,0.000000e+00,4.641746e-08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
75873,0.000000e+00,6.962619e-05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
75874,0.000000e+00,9.283492e-08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
75875,0.000000e+00,6.962619e-05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
75876,0.000000e+00,2.320873e-06,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
75877,0.000000e+00,4.641746e-08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
75878,0.000000e+00,3.249222e-07,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
75879,0.000000e+00,9.283492e-08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
75880,1.001282e-06,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
75881,0.000000e+00,2.320873e-07,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
75882,0.000000e+00,4.456076e-06,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
75883,0.000000e+00,2.098069e-05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
75884,1.039694e-06,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
75885,9.044825e-07,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
75886,4.440466e-07,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
75887,0.000000e+00,9.422744e-07,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
75888,1.024329e-05,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
75889,0.000000e+00,2.947973e-05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
75890,0.000000e+00,2.228038e-05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

### Creating a train / test split

In order to evaluate our model, we'll split our data into two groups, a group for training, which the neural net will learn on, and a group for validation, which the neural net will not see, but be validated against once trained.

In [392]:
X_train, X_test, y_train, y_test = train_test_split(data, labels, test_size=0.2)

In [393]:
print("X_train shape: ", X_train.shape)
print("X_test shape: ", X_test.shape)
print("y_train shape: ", y_train.shape)
print("y_test shape: ", y_test.shape)

X_train shape:  (60712, 9400)
X_test shape:  (15179, 9400)
y_train shape:  (60712, 12)
y_test shape:  (15179, 12)

### Building a simple model

We'll build a simple neural network which accepts our input of 9400 bits of data, and passes it to 6279 neurons in a hidden layer (two thirds of the input layer plus the output layer, is a good rule of thumb for how many neurons a hidden layer should have). Finally, our hidden layer is passed to an output layer representing our categories (so 12 neurons in this) and uses a softmax activation function to turn our predictions into probabilities of it being that class...

In [394]:
def build_model():
    model = Sequential()
    model.add(Dense(6279, input_dim=X_train.shape[1], activation='relu'))
    model.add(Dropout(0.1))
    model.add(Dense(y_train.shape[1], activation='softmax'))
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    
    return model

### Hyperparameters

In [395]:
epochs = 5
batch_size = 2000

Let's train our simple model...

In [396]:
model = build_model()
model.fit(X_train, y_train, epochs=epochs, batch_size=batch_size)

Epoch 1/5
60712/60712 [==============================] - 148s 2ms/step - loss: 0.7000 - acc: 0.7340
Epoch 2/5
60712/60712 [==============================] - 146s 2ms/step - loss: 0.3237 - acc: 0.8088
Epoch 3/5
60712/60712 [==============================] - 152s 3ms/step - loss: 0.2564 - acc: 0.8270
Epoch 4/5
60712/60712 [==============================] - 145s 2ms/step - loss: 0.2190 - acc: 0.8382
Epoch 5/5
60712/60712 [==============================] - 143s 2ms/step - loss: 0.1948 - acc: 0.8446

In [397]:
score = model.evaluate(X_test, y_test)

print("%s: %.2f%%" % (model.metrics_names[1], score[1]*100))

15179/15179 [==============================] - 31s 2ms/step
acc: 81.85%

### Predicting a Permit

Let's pick a random entry and see if our model can predict its Purpose successfully. You can play with the index to test our model on different permits...

In [543]:
index = 1 # Play with this to see how it predicts each permit...
permit = X_train.loc[[index]]

permit

,0,1,2,3,4,5,6,7,8,9,...,9390,9391,9392,9393,9394,9395,9396,9397,9398,9399
1,0.0,4.641746e-08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [544]:
actual = y_train.loc[[index]]
actual

   B  E  G  H  L  M  N  P  Q  S  T  Z
1  0  0  0  0  0  0  0  0  1  0  0  0

In [545]:
probabilities = model.predict(permit)
prediction    = np.argmax(probabilities)

print("Predicted: ", labels.columns[prediction])
print("Actual: ", max(actual.idxmax(axis=1)))

Predicted:  Q
Actual:  Q

### Evaluating our model with K-Fold Cross Validation

We'll use k-fold validation to get a better representation of how our model did...

In [398]:
k_fold    = StratifiedKFold(n_splits=10, shuffle=True, random_state=seed)
cv_scores = []

for train, test in kfold.split(data, labels):
    model = build_model()
    model.fit(data[train], labels[train], epochs=epochs, batch_size=10, verbose=0)
    scores = model.evaluate(data[test], labels[test], verbose=0)
    print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))
    
    cv_scores.append(scores[1] * 100)
    
print("%.2f%% (+/- %.2f%%)" % (numpy.mean(cv_scores), numpy.std(cv_scores)))

KeyError: '[ 9400  9401  9402 ... 75888 75889 75890] not in index'